#!/usr/bin/env bash

PATH=".:$PATH"

IMAGE_NAME=$1

TIMESTAMP=$(date +%s)
CURRENT_BRANCH=$(git branch --show-current)

FULL_IMAGE_NAME=quay.io/hbelmiro/"${IMAGE_NAME}":dev-"${CURRENT_BRANCH}"-"${TIMESTAMP}"

if docker build -t "${FULL_IMAGE_NAME}" . > /dev/null; then
  echo "${FULL_IMAGE_NAME}"
else
  echo "Container build failed."
  exit 1
fi