#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$0")"
source "$SCRIPT_DIR"/handle_error

USE_DOCKER=false

while getopts "d" opt; do
  case $opt in
    d)
      USE_DOCKER=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

IMAGE=""
if [ "$USE_DOCKER" = true ]; then
  IMAGE=$(h-docker-build-dev -d dspo) || handle_error "Failed to build Docker container image"
else
  IMAGE=$(h-docker-build-dev dspo) || handle_error "Failed to build Quay container image"
fi

docker push "$IMAGE" || handle_error "Failed to push container image"
make all deploy IMG="$IMAGE"