#!/usr/bin/env zsh

set -e

usage() {
  echo "Usage: $0 --image <image_base_name> --container-file <containerfile_path> --platform <platform> [-p]"
  exit 1
}

PUSH_IMAGE=false
PUSH_TO_KIND=false
REMOVE_IMAGE=false
PLATFORM=""
DEBUG=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --image)
      IMAGE_BASE_NAME="$2"
      shift 2
      ;;
    --container-file)
      CONTAINERFILE_PATH="$2"
      shift 2
      ;;
    --platform)
      PLATFORM="$2"
      shift 2
      ;;
    --debug)
      DEBUG="$2"
      shift 2
      ;;
    --kfp-distribution)
      KFP_DISTRIBUTION="$2"
      shift 2
      ;;
    --push)
      PUSH_IMAGE=true
      shift
      ;;
    --push-to-kind)
      PUSH_TO_KIND=true
      shift
      ;;
    --cluster-name)
      CLUSTER_NAME="$2"
      shift 2
      ;;
    --remove-image)
      REMOVE_IMAGE=true
      shift
      ;;
    *)
      usage
      ;;
  esac
done

if [ -z "$IMAGE_BASE_NAME" ] || [ -z "$CONTAINERFILE_PATH" ] || [ -z "$PLATFORM" ]; then
  usage
fi

TIMESTAMP=$(date +%s)
CURRENT_BRANCH=$(git branch --show-current)

FULL_IMAGE_NAME="${IMAGE_BASE_NAME}:dev-${CURRENT_BRANCH//\//_}-${TIMESTAMP}"

echo "${FULL_IMAGE_NAME}"

if [ "$DEBUG" = true ]; then
    CONTAINERFILE_PATH="${CONTAINERFILE_PATH}.debug.${KFP_DISTRIBUTION}"
fi

BUILD_CMD="podman build --platform=$PLATFORM -t \"${FULL_IMAGE_NAME}\" -f \"${CONTAINERFILE_PATH}\""

if eval "$BUILD_CMD" . ; then
  if [ "$PUSH_IMAGE" = true ]; then
    podman push "${FULL_IMAGE_NAME}"
  fi
  if [ "$PUSH_TO_KIND" = true ]; then
    if [ -z "$CLUSTER_NAME" ]; then
      echo "--cluster-name is required when --push-to-kind is set"
      exit 1
    fi
    kind load --name "${CLUSTER_NAME}" image-archive <(podman save "${FULL_IMAGE_NAME}")
  fi
else
  echo "Image build failed."
  exit 1
fi

if [ "$REMOVE_IMAGE" = true ]; then
    echo "Removing image..."
    podman rmi "${FULL_IMAGE_NAME}"
fi
