#!/usr/bin/env zsh

set -e

usage() {
  echo "Usage: $0 --platform <platform> [-p]"
  echo "  --platform  Set the target platform (mandatory)"
  echo "  -p         Push the image after building"
  exit 1
}

PUSH_OPTION=""
PLATFORM=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --platform)
      PLATFORM="$2"
      shift 2
      ;;
    -p)
      PUSH_OPTION="-p"
      shift
      ;;
    *)
      usage
      ;;
  esac
done

if [ -z "$PLATFORM" ]; then
  usage
fi

h-kfp-build-image --image quay.io/hbelmiro/dsp-scheduled-workflow --container-file ./backend/Dockerfile.scheduledworkflow --platform "$PLATFORM" ${PUSH_OPTION}