#!/usr/bin/env zsh

set -e

usage() {
  echo "Usage: $0 --platform <platform> --debug <true|false> --kfp-distribution <kfp|odh> [-p]"
  echo "  --platform          Set the target platform (mandatory)"
  echo "  --debug             Set if the image should be in debug mode (mandatory)"
  echo "  --kfp-distribution  Set the KFP distribution. Can be 'kfp' or 'odh' (mandatory)"
  echo "  --push              Push the image after building"
  echo "  --push-to-kind      Push the image to a Kind cluster after building"
  echo "  --cluster-name      Kind cluster name"
  echo "  --remove-image      Remove the image after building"
  exit 1
}

PUSH_OPTION=""
PLATFORM=""
DEBUG=false
PUSH_TO_KIND_OPTION=""
CLUSTER_NAME=""
REMOVE_IMAGE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --platform)
      PLATFORM="$2"
      shift 2
      ;;
    --debug)
      DEBUG="$2"
      shift 2
      ;;
    --kfp-distribution)
      KFP_DISTRIBUTION="$2"
      shift 2
      ;;
    --push)
      PUSH_OPTION="--push"
      shift
      ;;
    --push-to-kind)
      PUSH_TO_KIND_OPTION="--push-to-kind"
      shift
      ;;
    --cluster-name)
      CLUSTER_NAME="$2"
      shift 2
      ;;
    --remove-image)
      REMOVE_IMAGE="$2"
      shift 2
      ;;
    *)
      usage
      ;;
  esac
done

if [ -z "$PLATFORM" ]; then
  usage
fi

if [ -z "$CLUSTER_NAME" ]; then
  h-kfp-build-image --image quay.io/hbelmiro/dsp-api-server --container-file ./backend/Dockerfile --debug "${DEBUG}" --kfp-distribution "${KFP_DISTRIBUTION}" --platform "$PLATFORM" ${PUSH_OPTION} ${PUSH_TO_KIND_OPTION} --remove-image "${REMOVE_IMAGE}"
else
  h-kfp-build-image --image quay.io/hbelmiro/dsp-api-server --container-file ./backend/Dockerfile --debug "${DEBUG}" --kfp-distribution "${KFP_DISTRIBUTION}" --platform "$PLATFORM" ${PUSH_OPTION} ${PUSH_TO_KIND_OPTION} --cluster-name "${CLUSTER_NAME}" --remove-image "${REMOVE_IMAGE}"
fi