#!/bin/bash

set -e

SECRET_NAME="hbelmiro-pull-secret"
SERVICE_ACCOUNT_NAME="hbelmiro-service-account"

clean() {
  oc delete secret "$SECRET_NAME" --ignore-not-found
  oc delete serviceaccount "$SERVICE_ACCOUNT_NAME" --ignore-not-found
}

create_secret() {
  local DOCKER_CONFIG_PATH="$HOME/.docker/config.json"

  oc create secret generic "$SECRET_NAME" --from-file=.dockerconfigjson="$DOCKER_CONFIG_PATH" --type=kubernetes.io/dockerconfigjson
  echo "Secret '$SECRET_NAME' created successfully."
}

create_service_account() {
  oc create serviceaccount $SERVICE_ACCOUNT_NAME
  oc secrets link hbelmiro-service-account $SECRET_NAME --for=pull
}

add_service_account() {
  oc patch serviceaccount default -p "{\"imagePullSecrets\": [{\"name\": \"${SECRET_NAME}\"}]}"
}

main () {
  clean
  create_secret
  create_service_account
  add_service_account
}

main
